name: neoamphoric
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  csslib: ^0.17.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_slider_drawer: ^2.0.0
  flutter_svg: ^1.0.0
  get: 4.6.1
  simple_gradient_text: ^1.2.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/jpeg/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/static/Montserrat-Medium.ttf
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Semibold.ttf
  uses-material-design: true
